name: Sean Oliver
markdown: redcarpet
pygments: true

url: http://seanoliver.me

social:
  twitter: seanoliver
  facebook: seane
  linkedin: soliver87
  github: seanoliver
  plus: 107797469513631817514

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /
  - title: About
    url: /about
  - title: Subscribe
    url: /subscribe
  - title: Feed
    url: http://feeds.feedburner.com/seaneoliver
    external: true

permalink:   /:title